name: Desktop CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: desktop-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  NODE_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-node
        with:
          node-version: 18
          cache-dependency-path: package-lock.json
      - uses: ./.github/actions/setup-rust
      - name: Install dependencies
        run: npm ci
      - name: Lint (desktop)
        run: npm run lint -w apps/desktop
      - name: Type check (desktop)
        run: npx tsc -p apps/desktop/tsconfig.json --noEmit
      - name: Build shared package
        run: npm run build:shared
      - name: Build desktop app
        run: npm run build -w apps/desktop
